# Generated by Django 2.2.3 on 2019-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(max_length=55)),
                ('age', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Kisi'), ('M', 'Qadin')], max_length=55)),
                ('breed', models.CharField(max_length=55)),
                ('yem', models.CharField(max_length=55)),
            ],
        ),
    ]
