# Generated by Django 2.2.3 on 2019-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0003_auto_20190718_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='special_case',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='gender',
            field=models.CharField(choices=[('F', 'Erkək'), ('M', 'Dişi')], max_length=55),
        ),
    ]
