# Generated by Django 2.2.3 on 2019-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0004_auto_20190718_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='special_case',
            field=models.CharField(blank=True, choices=[('vitamin', 'Vitamin'), ('derman', 'Derman')], max_length=100, null=True),
        ),
    ]
