# Generated by Django 2.2.3 on 2019-07-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0005_auto_20190718_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='number',
            field=models.IntegerField(max_length=55, null=True),
        ),
    ]
