# Generated by Django 2.2.3 on 2019-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0007_infofields_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='age',
            field=models.CharField(max_length=55),
        ),
    ]
