# Generated by Django 2.2.3 on 2019-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0008_auto_20190723_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
