# Generated by Django 2.2.3 on 2019-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0010_auto_20190723_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
