# Generated by Django 2.2.3 on 2019-07-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0014_auto_20190724_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofields',
            name='number',
        ),
        migrations.AlterField(
            model_name='infofields',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkək'), ('D', 'Dişi')], max_length=55),
        ),
    ]
