# Generated by Django 2.2.3 on 2019-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0015_auto_20190724_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
