# Generated by Django 2.2.3 on 2019-07-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0016_infofields_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
