# Generated by Django 2.2.3 on 2019-07-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0017_infofields_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infofields',
            old_name='num',
            new_name='sira',
        ),
    ]
