# Generated by Django 2.2.3 on 2019-07-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0018_auto_20190724_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofields',
            name='sira',
        ),
    ]
