# Generated by Django 2.2.3 on 2019-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0019_remove_infofields_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofields',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
