# Generated by Django 2.2.3 on 2019-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0020_infofields_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
    ]
