# Generated by Django 2.2.3 on 2019-07-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0021_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
