# Generated by Django 2.2.3 on 2019-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0022_delete_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('age', models.CharField(max_length=255)),
            ],
        ),
    ]
