# Generated by Django 2.2.3 on 2019-07-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0023_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
