# Generated by Django 2.2.3 on 2019-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0025_auto_20190730_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='special_case',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
