# Generated by Django 2.2.3 on 2019-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0026_auto_20190730_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variants', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
