# Generated by Django 2.2.3 on 2019-08-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0027_select'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Select',
        ),
    ]
