# Generated by Django 2.2.3 on 2019-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0028_delete_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
