# Generated by Django 2.2.3 on 2019-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0030_auto_20190801_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='breed',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='feed',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='gender',
            field=models.CharField(blank=True, choices=[('E', 'Erkək'), ('D', 'Dişi')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
