# Generated by Django 2.2.3 on 2019-08-09 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0031_auto_20190809_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
