# Generated by Django 2.2.3 on 2019-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0032_auto_20190809_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infofields',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
