# Generated by Django 2.2.3 on 2019-09-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0033_auto_20190809_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
