# Generated by Django 2.2.3 on 2019-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_set', '0034_auto_20190909_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofields',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
